// 配置方法
import './src/font.js'
// 弹窗
import './src/notice.js'
// 路由
import './src/router.js'
// 发送请求
import './src/axios.js'
// 获取地理位置
import './src/geo.js'
// 获取相机信息
import './src/camera.js'
// 设置导航
import './src/nav.js'
// 支付相关
import './src/pay.js'
// 存储相关
import './src/storage.js'
// 全局事件
import './src/events.js'
// 分享
import './src/share.js'
// 工具方法
import './src/tools.js'